import { Note } from "../../db-actions";

export const database = {
  notes: [],
};
export const notes: Note[] = [
  {
    _id: "123",
    books: [
      {
        isbn: "0520203259",
        title: "Hellenistic history and culture",
        author: "Peter Green",

        editor: "",

        price: 10,

        note: "",
        quantity: 3,
      },
      {
        isbn: "0300088108",
        title: "Plutarch",
        author: "Robert Lamberton",

        editor: "",

        price: 11,

        note: "",
        quantity: 3,
      },
    ],
  },
  {
    // or could be generated by pouch
    _id: "456",
    books: [
      {
        isbn: "0500400288",
        title: "Philip II and Macedonian imperialism",
        author: "John R. Ellis",
        editor: "",

        price: 10,

        note: "",
        quantity: 3,
      },
      {
        isbn: "0300088108",
        title: "Plutarch",
        author: "Robert Lamberton",

        editor: "",

        price: 11,

        note: "",
        quantity: 3,
      },
    ],
  },
  {
    // or could be generated by pouch
    _id: "789",
    books: [
      {
        isbn: "0140445625",
        title: "A short account of the destruction of the Indies",
        author: "Bartolomé de las Casas",
        editor: "",

        price: 14,

        note: "",
        quantity: 1,
      },
    ],
  },
];
export const note: Note = {
  // or could be generated by pouch
  _id: "123",
  books: [
    {
      isbn: "0520203259",
      title: "Hellenistic history and culture",
      author: "Peter Green",

      editor: "",

      price: 10,

      note: "",
      quantity: 3,
    },
    {
      isbn: "0300088108",
      title: "Plutarch",
      author: "Robert Lamberton",

      editor: "",

      price: 11,

      note: "",
      quantity: 3,
    },
    {
      isbn: "0520204832",
      title: "Studies in Greek culture and Roman policy",
      author: "Erich S. Gruen",
      editor: "",

      price: 14,

      note: "",
      quantity: 1,
    },
  ],
};

const newBook = {
  isbn: "1555406211",
  title: "Latin in American schools : teaching the ancient world",
  author: "Sally Davis",
  editor: "",

  price: 14,

  note: "",
  quantity: 1,
};
export const databaseWithNote = {
  notes: [note],
};
export const updatedNote = { ...note, books: note.books.concat(newBook) };

export const databaseWithUpdatedNote = {
  notes: [updatedNote],
};
