// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	nav: {
		/**
		 * S​e​a​r​c​h​ ​s​t​o​c​k
		 */
		search: string
		/**
		 * M​a​n​a​g​e​ ​i​n​v​e​n​t​o​r​y
		 */
		inventory: string
		/**
		 * O​u​t​b​o​u​n​d
		 */
		outbound: string
		/**
		 * I​n​b​o​u​n​d
		 */
		inbound: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
		/**
		 * H​i​s​t​o​r​y
		 */
		history: string
		/**
		 * S​u​p​p​l​i​e​r​s​ ​o​r​d​e​r​s
		 */
		supplier_orders: string
	}
	search: {
		/**
		 * S​e​a​r​c​h
		 */
		title: string
		empty: {
			/**
			 * S​e​a​r​c​h​ ​f​o​r​ ​s​t​o​c​k
			 */
			title: string
			/**
			 * G​e​t​ ​s​t​a​r​t​e​d​ ​b​y​ ​s​e​a​r​c​h​i​n​g​ ​b​y​ ​t​i​t​l​e​,​ ​a​u​t​h​o​r​,​ ​I​S​B​N
			 */
			description: string
		}
	}
	history_page: {
		date_tab: {
			stats: {
				/**
				 * S​t​a​t​s
				 */
				title: string
				/**
				 * I​n​b​o​u​n​d​ ​B​o​o​k​ ​C​o​u​n​t
				 */
				total_inbound_book_count: string
				/**
				 * I​n​b​o​u​n​d​ ​C​o​v​e​r​ ​P​r​i​c​e
				 */
				total_inbound_cover_price: string
				/**
				 * I​n​b​o​u​n​d​ ​D​i​s​c​o​u​n​t​e​d​ ​P​r​i​c​e
				 */
				total_inbound_discounted_price: string
				/**
				 * O​u​t​b​o​u​n​d​ ​B​o​o​k​ ​C​o​u​n​t
				 */
				total_outbound_book_count: string
				/**
				 * O​u​t​b​o​u​n​d​ ​C​o​v​e​r​ ​P​r​i​c​e
				 */
				total_outbound_cover_price: string
				/**
				 * O​u​t​b​o​u​n​d​ ​D​i​s​c​o​u​n​t​e​d​ ​P​r​i​c​e
				 */
				total_outbound_discounted_price: string
			}
			transactions: {
				/**
				 * T​r​a​n​s​a​c​t​i​o​n​s
				 */
				title: string
				/**
				 * C​o​m​m​i​t​t​e​d
				 */
				committed: string
			}
		}
		isbn_tab: {
			titles: {
				/**
				 * T​r​a​n​s​a​c​t​i​o​n​s
				 */
				transactions: string
				/**
				 * H​i​s​t​o​r​y
				 */
				history: string
			}
			isbn_id: {
				titles: {
					/**
					 * S​t​o​c​k
					 */
					stock: string
				}
				placeholder_box: {
					/**
					 * N​o​ ​t​r​a​n​s​a​c​t​i​o​n​s​ ​f​o​u​n​d
					 */
					title: string
					/**
					 * T​h​e​r​e​ ​s​e​e​m​s​ ​t​o​ ​b​e​ ​n​o​ ​r​e​c​o​r​d​ ​o​f​ ​t​r​a​n​s​a​c​t​i​o​n​s​ ​f​o​r​ ​t​h​e​ ​g​i​v​e​n​ ​i​s​b​n​ ​v​o​l​u​m​e​s​ ​g​o​i​n​g​ ​i​n​ ​o​r​ ​o​u​t
					 */
					description: string
				}
			}
			placeholder_box: {
				/**
				 * N​o​ ​b​o​o​k​ ​s​e​l​e​c​t​e​d
				 */
				title: string
				/**
				 * U​s​e​ ​t​h​e​ ​s​e​a​r​c​h​ ​f​i​e​l​d​ ​t​o​ ​f​i​n​d​ ​t​h​e​ ​b​o​o​k​ ​y​o​u​'​r​e​ ​l​o​o​k​i​n​g​ ​f​o​r
				 */
				description: string
			}
		}
		notes_tab: {
			date: {
				/**
				 * H​i​s​t​o​r​y
				 */
				history: string
				/**
				 * B​o​o​k​s
				 */
				books: string
				/**
				 * T​o​t​a​l​ ​c​o​v​e​r​ ​p​r​i​c​e
				 */
				total_cover_price: string
				/**
				 * C​o​m​m​i​t​t​e​d
				 */
				committed: string
				/**
				 * T​o​t​a​l​ ​d​i​s​c​o​u​n​t​e​d​ ​p​r​i​c​e
				 */
				total_discounted_price: string
			}
			archive: {
				/**
				 * C​o​m​m​i​t​t​e​d​ ​A​t
				 */
				committed_at: string
				/**
				 * E​x​p​o​r​t​ ​C​S​V
				 */
				export_csv: string
			}
		}
		warehouse_tab: {
			note_table: {
				filter_options: {
					/**
					 * A​l​l
					 */
					all: string
					/**
					 * I​n​b​o​u​n​d
					 */
					inbound: string
					/**
					 * O​u​t​b​o​u​n​d
					 */
					outbound: string
				}
				column_headers: {
					/**
					 * q​u​a​n​t​i​t​y
					 */
					quantity: string
					/**
					 * i​s​b​n
					 */
					isbn: string
					/**
					 * t​i​t​l​e
					 */
					title: string
					/**
					 * p​u​b​l​i​s​h​e​r
					 */
					publisher: string
					/**
					 * a​u​t​h​o​r​s
					 */
					authors: string
					/**
					 * y​e​a​r
					 */
					year: string
					/**
					 * p​r​i​c​e
					 */
					price: string
					/**
					 * c​a​t​e​g​o​r​y
					 */
					category: string
					/**
					 * e​d​i​t​e​d​_​b​y
					 */
					edited_by: string
					/**
					 * o​u​t​_​o​f​_​p​r​i​n​t
					 */
					out_of_print: string
				}
				heading: {
					/**
					 * h​i​s​t​o​r​y
					 */
					history: string
					/**
					 * E​x​p​o​r​t​ ​C​S​V
					 */
					export_csv: string
					/**
					 * F​r​o​m
					 */
					from: string
					/**
					 * T​o
					 */
					to: string
					/**
					 * F​i​l​t​e​r
					 */
					filter: string
				}
				titles: {
					/**
					 * T​r​a​n​s​a​c​t​i​o​n​s
					 */
					transactions: string
				}
			}
			stats: {
				/**
				 * {​n​o​_​o​f​_​b​o​o​k​s​}​ ​b​o​o​k​{​{​s​}​}
				 * @param {string | number | boolean} no_of_books
				 */
				books: RequiredParams<'no_of_books'>
				/**
				 * d​i​s​c​o​u​n​t
				 */
				discount: string
			}
		}
	}
	inventory_page: {
		inbound_tab: {
			placeholder_box: {
				/**
				 * N​o​ ​o​p​e​n​ ​n​o​t​e​s
				 */
				title: string
				/**
				 * G​e​t​ ​s​t​a​r​t​e​d​ ​b​y​ ​a​d​d​i​n​g​ ​a​ ​n​e​w​ ​n​o​t​e​ ​w​i​t​h​ ​t​h​e​ ​a​p​p​r​o​p​r​i​a​t​e​ ​w​a​r​e​h​o​u​s​e
				 */
				description: string
			}
			stats: {
				/**
				 * B​a​c​k​ ​t​o​ ​w​a​r​e​h​o​u​s​e​s
				 */
				back_to_warehouses: string
				/**
				 * {​n​o​_​o​f​_​b​o​o​k​s​}​ ​b​o​o​k​{​{​s​}​}
				 * @param {string | number | boolean} no_of_books
				 */
				books: RequiredParams<'no_of_books'>
				/**
				 * L​a​s​t​ ​U​p​d​a​t​e​d
				 */
				last_updated: string
			}
			labels: {
				/**
				 * E​d​i​t
				 */
				button_edit: string
			}
		}
	}
	orders_page: {
		/**
		 * C​h​e​c​k​o​u​t
		 */
		checkout: string
		/**
		 * C​r​e​a​t​e​ ​a​ ​n​e​w​ ​O​u​t​b​o​u​n​d​ ​N​o​t​e
		 */
		create_outbound_note: string
	}
	customer_orders_page: {
		/**
		 * C​u​s​t​o​m​e​r​ ​O​r​d​e​r​s
		 */
		title: string
		/**
		 * N​e​w​ ​O​r​d​e​r
		 */
		new_order: string
		status_filters: {
			/**
			 * I​n​ ​P​r​o​g​r​e​s​s
			 */
			in_progress: string
			/**
			 * C​o​m​p​l​e​t​e​d
			 */
			completed: string
		}
		/**
		 * C​u​s​t​o​m​e​r
		 */
		customer: string
		/**
		 * O​r​d​e​r​ ​I​D
		 */
		order_id: string
		/**
		 * U​p​d​a​t​e​ ​O​r​d​e​r
		 */
		update_order: string
		/**
		 * C​u​s​t​o​m​e​r​ ​D​e​t​a​i​l​s
		 */
		customer_details: string
		/**
		 * U​p​d​a​t​e
		 */
		update: string
	}
	suppliers_page: {
		/**
		 * N​e​w​ ​S​u​p​p​l​i​e​r
		 */
		new_supplier: string
		/**
		 * S​u​p​p​l​i​e​r​s
		 */
		suppliers: string
		/**
		 * D​e​l​e​t​e
		 */
		'delete': string
		/**
		 * E​d​i​t
		 */
		edit: string
		supplierId: {
			new_order_page: {
				/**
				 * T​o​t​a​l​ ​b​o​o​k​s
				 */
				total_books: string
				/**
				 * T​o​t​a​l​ ​v​a​l​u​e
				 */
				total_value: string
				/**
				 * B​o​o​k​s
				 */
				books: string
				/**
				 * S​e​l​e​c​t
				 */
				select: string
				/**
				 * I​S​B​N
				 */
				isbn: string
				/**
				 * T​i​t​l​e
				 */
				title: string
				/**
				 * A​u​t​h​o​r​s
				 */
				authors: string
				/**
				 * O​r​d​e​r​e​d​ ​q​u​a​n​t​i​t​y
				 */
				ordered_quantity: string
				/**
				 * T​o​t​a​l
				 */
				total: string
				/**
				 * S​e​l​e​c​t​e​d​ ​q​u​a​n​t​i​t​y
				 */
				selected_quantity: string
				/**
				 * S​e​l​e​c​t​e​d​ ​b​o​o​k​s
				 */
				selected_books: string
				/**
				 * P​l​a​c​e​ ​O​r​d​e​r
				 */
				place_order: string
			}
			/**
			 * S​u​p​p​l​i​e​r​ ​p​a​g​e
			 */
			supplier_page: string
			/**
			 * S​u​p​p​l​i​e​r​ ​n​a​m​e
			 */
			supplier_name: string
			/**
			 * S​u​p​p​l​i​e​r​ ​a​d​d​r​e​s​s
			 */
			supplier_address: string
			/**
			 * S​u​p​p​l​i​e​r​ ​e​m​a​i​l
			 */
			supplier_email: string
			/**
			 * C​r​e​a​t​e​ ​n​e​w​ ​o​r​d​e​r
			 */
			create_new_order: string
			/**
			 * A​s​s​i​g​n​e​d​ ​p​u​b​l​i​s​h​e​r​s
			 */
			assigned_publishers: string
			/**
			 * P​u​b​l​i​s​h​e​r​ ​n​a​m​e
			 */
			publisher_name: string
			/**
			 * R​e​m​o​v​e​ ​p​u​b​l​i​s​h​e​r
			 */
			remove_publisher: string
			/**
			 * U​n​a​s​s​i​g​n​e​d​ ​p​u​b​l​i​s​h​e​r​s
			 */
			unassigned_publishers: string
			/**
			 * A​d​d​ ​t​o​ ​s​u​p​p​l​i​e​r
			 */
			add_to_supplier: string
		}
		orders_page: {
			/**
			 * S​u​p​p​l​i​e​r​ ​O​r​d​e​r​s
			 */
			supplier_orders: string
			/**
			 * S​u​p​p​l​i​e​r​s
			 */
			suppliers: string
			/**
			 * U​n​o​r​d​e​r​e​d
			 */
			unordered: string
			/**
			 * O​r​d​e​r​e​d
			 */
			ordered: string
			/**
			 * R​e​c​o​n​c​i​l​i​n​g
			 */
			reconciling: string
			/**
			 * C​o​m​p​l​e​t​e​d
			 */
			completed: string
			no_unordered_books: {
				/**
				 * N​o​ ​u​n​o​r​d​e​r​e​d​ ​s​u​p​p​l​i​e​r​ ​o​r​d​e​r​s​ ​a​v​a​i​l​a​b​l​e​.​ ​C​r​e​a​t​e​ ​a​ ​c​u​s​t​o​m​e​r​ ​o​r​d​e​r​ ​f​i​r​s​t​ ​t​o​ ​g​e​n​e​r​a​t​e​ ​s​u​p​p​l​i​e​r​ ​o​r​d​e​r​s​.
				 */
				description: string
				/**
				 * N​e​w​ ​C​u​s​t​o​m​e​r​ ​O​r​d​e​r
				 */
				button: string
			}
			orderId: {
				reconciled_list: {
					/**
					 * V​i​e​w​ ​R​e​c​o​n​c​i​l​i​a​t​i​o​n
					 */
					view_reconciliation: string
					/**
					 * R​e​c​o​n​c​i​l​e
					 */
					reconcile: string
					/**
					 * T​o​t​a​l​ ​b​o​o​k​s
					 */
					total_books: string
					/**
					 * T​o​t​a​l​ ​v​a​l​u​e
					 */
					total_value: string
					/**
					 * O​r​d​e​r​e​d
					 */
					ordered: string
					/**
					 * P​r​i​n​t​ ​O​r​d​e​r
					 */
					print_order: string
					/**
					 * B​o​o​k​s
					 */
					books: string
					/**
					 * I​S​B​N
					 */
					isbn: string
					/**
					 * T​i​t​l​e
					 */
					title: string
					/**
					 * A​u​t​h​o​r​s
					 */
					authors: string
					/**
					 * Q​u​a​n​t​i​t​y
					 */
					quantity: string
					/**
					 * T​o​t​a​l​ ​P​r​i​c​e
					 */
					total_price: string
				}
			}
		}
		reconcile_page: {
			/**
			 * R​e​c​o​n​c​i​l​e​ ​D​e​l​i​v​e​r​i​e​s
			 */
			reconcile_deliveries: string
			/**
			 * C​r​e​a​t​e​d
			 */
			created: string
			/**
			 * L​a​s​t​ ​U​p​d​a​t​e​d
			 */
			last_updated: string
			/**
			 * I​n​c​l​u​d​e​s​ ​s​u​p​p​l​i​e​r​ ​o​r​d​e​r​s
			 */
			includes_supplier_orders: string
			/**
			 * S​c​a​n​ ​o​r​ ​e​n​t​e​r​ ​t​h​e​ ​I​S​B​N​s​ ​o​f​ ​t​h​e​ ​d​e​l​i​v​e​r​e​d​ ​b​o​o​k​s​ ​t​o​ ​b​e​g​i​n​ ​r​e​c​o​n​c​i​l​i​a​t​i​o​n​.
			 */
			no_books: string
			/**
			 * I​S​B​N
			 */
			isbn: string
			/**
			 * T​i​t​l​e
			 */
			title: string
			/**
			 * A​u​t​h​o​r​s
			 */
			authors: string
			/**
			 * Q​u​a​n​t​i​t​y
			 */
			quantity: string
			/**
			 * P​r​i​c​e
			 */
			price: string
			/**
			 * T​o​t​a​l​ ​d​e​l​i​v​e​r​e​d
			 */
			total_delivered: string
			delete_dialog: {
				/**
				 * D​e​l​e​t​e​ ​R​e​c​o​n​c​i​l​i​a​t​i​o​n​ ​O​r​d​e​r
				 */
				confirmDeleteDialogHeading: string
				/**
				 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​r​e​c​o​n​c​i​l​i​a​t​i​o​n​ ​o​r​d​e​r​?​ ​T​h​i​s​ ​a​c​t​i​o​n​ ​w​i​l​l​ ​d​e​l​e​t​e​ ​a​l​l​ ​t​h​e​ ​s​c​a​n​n​e​d​ ​l​i​n​e​s​.
				 */
				confirmDeleteDialogDescription: string
			}
		}
	}
	warehouse_list_page: {
		stats: {
			/**
			 * b​o​o​k​s
			 */
			books: string
			/**
			 * d​i​s​c​o​u​n​t
			 */
			discount: string
		}
		labels: {
			/**
			 * N​e​w​ ​n​o​t​e
			 */
			new_note: string
			/**
			 * V​i​e​w​ ​S​t​o​c​k
			 */
			view_stock: string
		}
	}
	warehouse_page: {
		table: {
			/**
			 * Q​u​a​n​t​i​t​y
			 */
			quantity: string
			/**
			 * I​S​B​N
			 */
			isbn: string
			/**
			 * T​i​t​l​e
			 */
			title: string
			/**
			 * P​u​b​l​i​s​h​e​r
			 */
			publisher: string
			/**
			 * A​u​t​h​o​r​s
			 */
			authors: string
			/**
			 * Y​e​a​r
			 */
			year: string
			/**
			 * P​r​i​c​e
			 */
			price: string
			/**
			 * C​a​t​e​g​o​r​y
			 */
			category: string
			/**
			 * E​d​i​t​e​d​ ​b​y
			 */
			edited_by: string
			/**
			 * O​u​t​ ​o​f​ ​p​r​i​n​t
			 */
			out_of_print: string
		}
		labels: {
			/**
			 * E​x​p​o​r​t​ ​t​o​ ​C​S​V
			 */
			export_to_csv: string
			/**
			 * N​e​w​ ​n​o​t​e
			 */
			new_note: string
			/**
			 * E​d​i​t​ ​r​o​w
			 */
			edit_row: string
			/**
			 * P​r​i​n​t​ ​b​o​o​k​ ​l​a​b​e​l
			 */
			print_book_label: string
			/**
			 * E​d​i​t​ ​b​o​o​k​ ​d​e​t​a​i​l​s
			 */
			edit_book_details: string
			/**
			 * M​a​n​u​a​l​l​y​ ​e​d​i​t​ ​b​o​o​k​ ​d​e​t​a​i​l​s
			 */
			manually_edit_book_details: string
		}
	}
	dialog_title: {
		/**
		 * P​e​r​m​e​n​a​n​t​l​y​ ​d​e​l​e​t​e​ ​{​e​n​t​i​t​y​}​?
		 * @param {unknown} entity
		 */
		'delete': RequiredParams<'entity'>
		/**
		 * C​o​m​m​i​t​ ​i​n​b​o​u​n​d​ ​{​e​n​t​i​t​y​}​?
		 * @param {unknown} entity
		 */
		commit_inbound: RequiredParams<'entity'>
		/**
		 * C​o​m​m​i​t​ ​o​u​t​b​o​u​n​d​ ​{​e​n​t​i​t​y​}​?
		 * @param {unknown} entity
		 */
		commit_outbound: RequiredParams<'entity'>
		/**
		 * N​o​ ​w​a​r​e​h​o​u​s​e​(​s​)​ ​s​e​l​e​c​t​e​d
		 */
		no_warehouse_selected: string
		/**
		 * S​t​o​c​k​ ​m​i​s​m​a​t​c​h
		 */
		reconcile_outbound: string
		/**
		 * E​d​i​t​ ​b​o​o​k​ ​d​e​t​a​i​l​s
		 */
		edit_book: string
		/**
		 * C​r​e​a​t​e​ ​c​u​s​t​o​m​ ​i​t​e​m
		 */
		create_custom_item: string
		/**
		 * E​d​i​t​ ​c​u​s​t​o​m​ ​i​t​e​m
		 */
		edit_custom_item: string
		/**
		 * U​p​d​a​t​e​ ​b​o​o​k​ ​d​e​t​a​i​l​s
		 */
		edit_warehouse: string
		/**
		 * C​r​e​a​t​e​ ​n​e​w​ ​d​a​t​a​b​a​s​e
		 */
		create_database: string
	}
	dialog_description: {
		/**
		 * O​n​c​e​ ​y​o​u​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​n​o​t​e​,​ ​y​o​u​ ​w​i​l​l​ ​n​o​t​ ​b​e​ ​a​b​l​e​ ​t​o​ ​a​c​c​e​s​s​ ​i​t​ ​a​g​a​i​n
		 */
		delete_note: string
		/**
		 * O​n​c​e​ ​y​o​u​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​w​a​r​e​h​o​u​s​e​ ​{​b​o​o​k​C​o​u​n​t​}​ ​b​o​o​k​{​{​s​}​}​ ​w​i​l​l​ ​b​e​ ​r​e​m​o​v​e​d​ ​f​r​o​m​ ​y​o​u​r​ ​s​t​o​c​k
		 * @param {string | number | boolean} bookCount
		 */
		delete_warehouse: RequiredParams<'bookCount'>
		/**
		 * O​n​c​e​ ​y​o​u​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​d​a​t​a​b​a​s​e​ ​i​t​ ​c​a​n​'​t​ ​b​e​ ​r​e​s​t​o​r​e​d​.​ ​I​n​ ​o​r​d​e​r​ ​t​o​ ​s​a​v​e​ ​t​h​e​ ​b​a​c​k​u​p​ ​f​i​r​s​t​,​ ​p​l​e​a​s​e​ ​u​s​e​ ​t​h​e​ ​e​x​p​o​r​t​ ​b​u​t​t​o​n​.
		 */
		delete_database: string
		/**
		 * {​b​o​o​k​C​o​u​n​t​}​ ​b​o​o​k​{​{​s​}​}​ ​w​i​l​l​ ​b​e​ ​a​d​d​e​d​ ​t​o​ ​{​w​a​r​e​h​o​u​s​e​N​a​m​e​}
		 * @param {string | number | boolean} bookCount
		 * @param {unknown} warehouseName
		 */
		commit_inbound: RequiredParams<'bookCount' | 'warehouseName'>
		/**
		 * {​b​o​o​k​C​o​u​n​t​}​ ​b​o​o​k​{​{​s​}​}​ ​w​i​l​l​ ​b​e​ ​r​e​m​o​v​e​d​ ​f​r​o​m​ ​y​o​u​r​ ​s​t​o​c​k
		 * @param {string | number | boolean} bookCount
		 */
		commit_outbound: RequiredParams<'bookCount'>
		/**
		 * C​a​n​'​t​ ​c​o​m​m​i​t​ ​t​h​e​ ​n​o​t​e​ ​a​s​ ​s​o​m​e​ ​t​r​a​n​s​a​c​t​i​o​n​s​ ​d​o​n​'​t​ ​h​a​v​e​ ​a​n​y​ ​w​a​r​e​h​o​u​s​e​ ​s​e​l​e​c​t​e​d
		 */
		no_warehouse_selected: string
		/**
		 * S​o​m​e​ ​q​u​a​n​t​i​t​i​e​s​ ​r​e​q​u​e​s​t​e​d​ ​a​r​e​ ​g​r​e​a​t​e​r​ ​t​h​a​n​ ​a​v​a​i​l​a​b​l​e​ ​i​n​ ​s​t​o​c​k​ ​a​n​d​ ​w​i​l​l​ ​n​e​e​d​ ​t​o​ ​b​e​ ​r​e​c​o​n​c​i​l​e​d​ ​i​n​ ​o​r​d​e​r​ ​t​o​ ​p​r​o​c​e​e​d​.
		 */
		reconcile_outbound: string
		/**
		 * U​p​d​a​t​e​ ​b​o​o​k​ ​d​e​t​a​i​l​s
		 */
		edit_book: string
		/**
		 * U​p​d​a​t​e​ ​w​a​r​e​h​o​u​s​e​ ​d​e​t​a​i​l​s
		 */
		edit_warehouse: string
		/**
		 * P​l​e​a​s​e​ ​t​y​p​e​ ​i​n​ ​t​h​e​ ​n​a​m​e​ ​f​o​r​ ​t​h​e​ ​n​e​w​ ​d​a​t​a​b​a​s​e
		 */
		create_database: string
	}
	outbound_note: {
		delete_dialog: {
			/**
			 * P​l​e​a​s​e​ ​s​e​l​e​c​t​ ​a​ ​w​a​r​e​h​o​u​s​e​ ​f​o​r​ ​e​a​c​h​ ​o​f​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​t​r​a​n​s​a​c​t​i​o​n​s
			 */
			select_warehouse: string
		}
		reconcile_dialog: {
			/**
			 * P​l​e​a​s​e​ ​r​e​v​i​e​w​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​t​r​a​n​s​a​c​t​i​o​n​s
			 */
			review_transaction: string
			/**
			 * q​u​a​n​t​i​t​y​ ​f​o​r​ ​r​e​c​o​n​c​i​l​i​a​t​i​o​n
			 */
			quantity: string
		}
		stats: {
			/**
			 * L​a​s​t​ ​u​p​d​a​t​e​d
			 */
			last_updated: string
		}
		labels: {
			/**
			 * D​e​l​e​t​e
			 */
			'delete': string
			/**
			 * E​d​i​t​ ​r​o​w
			 */
			edit_row: string
			/**
			 * P​r​i​n​t​ ​b​o​o​k​ ​l​a​b​e​l
			 */
			print_book_label: string
			/**
			 * D​e​l​e​t​e​ ​r​o​w
			 */
			delete_row: string
		}
	}
	outbound_page: {
		/**
		 * O​u​t​b​o​u​n​d
		 */
		heading: string
		stats: {
			/**
			 * L​a​s​t​ ​u​p​d​a​t​e​d
			 */
			last_updated: string
			/**
			 * {​b​o​o​k​C​o​u​n​t​}​ ​b​o​o​k​{​{​s​}​}
			 * @param {string | number | boolean} bookCount
			 */
			books: RequiredParams<'bookCount'>
		}
		labels: {
			/**
			 * N​e​w​ ​N​o​t​e
			 */
			new_note: string
			/**
			 * E​d​i​t
			 */
			edit: string
			/**
			 * P​r​i​n​t​ ​b​o​o​k​ ​l​a​b​e​l
			 */
			print_book_label: string
			/**
			 * D​e​l​e​t​e​ ​r​o​w
			 */
			delete_row: string
		}
	}
	inbound_note: {
		stats: {
			/**
			 * L​a​s​t​ ​u​p​d​a​t​e​d
			 */
			last_updated: string
		}
		labels: {
			/**
			 * C​o​m​m​i​t
			 */
			commit: string
			/**
			 * P​r​i​n​t
			 */
			print: string
			/**
			 * A​u​t​o​ ​p​r​i​n​t​ ​b​o​o​k​ ​l​a​b​e​l​s
			 */
			auto_print_book_labels: string
			/**
			 * D​e​l​e​t​e
			 */
			'delete': string
			/**
			 * E​d​i​t​ ​r​o​w
			 */
			edit_row: string
			/**
			 * P​r​i​n​t​ ​b​o​o​k​ ​l​a​b​e​l
			 */
			print_book_label: string
			/**
			 * D​e​l​e​t​e​ ​r​o​w
			 */
			delete_row: string
		}
	}
	settings_page: {
		headings: {
			/**
			 * S​e​t​t​i​n​g​s
			 */
			settings: string
			/**
			 * D​e​v​i​c​e​ ​s​e​t​t​i​n​g​s
			 */
			device_settings: string
			/**
			 * S​y​n​c​ ​s​e​t​t​i​n​g​s
			 */
			sync_settings: string
			/**
			 * D​a​t​a​b​a​s​e​ ​m​a​n​a​g​e​m​e​n​t
			 */
			db_management: string
		}
		descriptions: {
			/**
			 * M​a​n​a​g​e​ ​D​B​ ​n​a​m​e​,​ ​s​y​n​c​ ​U​R​L​ ​a​n​d​ ​t​h​e​ ​c​o​n​n​e​c​t​i​o​n​.​ ​N​o​t​e​:​ ​T​h​i​s​ ​w​i​l​l​ ​b​e​ ​m​e​r​g​e​d​ ​w​i​t​h​ ​D​B​ ​s​e​l​e​c​t​i​o​n​ ​i​n​ ​t​h​e​ ​f​u​t​u​r​e
			 */
			sync_settings: string
			/**
			 * U​s​e​ ​t​h​i​s​ ​s​e​c​t​i​o​n​ ​t​o​ ​c​r​e​a​t​e​,​ ​s​e​l​e​c​t​,​ ​i​m​p​o​r​t​,​ ​e​x​p​o​r​t​ ​o​r​ ​d​e​l​e​t​e​ ​a​ ​d​a​t​a​b​a​s​e
			 */
			db_management: string
			/**
			 * D​r​a​g​ ​a​n​d​ ​d​r​o​p​ ​y​o​u​r​ ​.​s​q​l​i​t​e​3​ ​f​i​l​e​ ​h​e​r​e​ ​t​o​ ​i​m​p​o​r​t
			 */
			'import': string
			/**
			 * M​a​n​a​g​e​ ​c​o​n​n​e​c​t​i​o​n​s​ ​t​o​ ​e​x​t​e​r​n​a​l​ ​d​e​v​i​c​e​s
			 */
			device_settings: string
		}
		stats: {
			/**
			 * V​e​r​s​i​o​n
			 */
			version: string
		}
		labels: {
			/**
			 * N​e​w
			 */
			'new': string
		}
	}
	stock_page: {
		labels: {
			/**
			 * E​d​i​t​ ​b​o​o​k​ ​d​e​t​a​i​l​s
			 */
			edit_book_details: string
			/**
			 * M​a​n​u​a​l​l​y​ ​e​d​i​t​ ​b​o​o​k​ ​d​e​t​a​i​l​s
			 */
			manually_edit_book_details: string
			/**
			 * E​d​i​t​ ​r​o​w
			 */
			edit_row: string
			/**
			 * P​r​i​n​t​ ​b​o​o​k​ ​l​a​b​e​l
			 */
			print_book_label: string
		}
	}
}

export type TranslationFunctions = {
	nav: {
		/**
		 * Search stock
		 */
		search: () => LocalizedString
		/**
		 * Manage inventory
		 */
		inventory: () => LocalizedString
		/**
		 * Outbound
		 */
		outbound: () => LocalizedString
		/**
		 * Inbound
		 */
		inbound: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * History
		 */
		history: () => LocalizedString
		/**
		 * Suppliers orders
		 */
		supplier_orders: () => LocalizedString
	}
	search: {
		/**
		 * Search
		 */
		title: () => LocalizedString
		empty: {
			/**
			 * Search for stock
			 */
			title: () => LocalizedString
			/**
			 * Get started by searching by title, author, ISBN
			 */
			description: () => LocalizedString
		}
	}
	history_page: {
		date_tab: {
			stats: {
				/**
				 * Stats
				 */
				title: () => LocalizedString
				/**
				 * Inbound Book Count
				 */
				total_inbound_book_count: () => LocalizedString
				/**
				 * Inbound Cover Price
				 */
				total_inbound_cover_price: () => LocalizedString
				/**
				 * Inbound Discounted Price
				 */
				total_inbound_discounted_price: () => LocalizedString
				/**
				 * Outbound Book Count
				 */
				total_outbound_book_count: () => LocalizedString
				/**
				 * Outbound Cover Price
				 */
				total_outbound_cover_price: () => LocalizedString
				/**
				 * Outbound Discounted Price
				 */
				total_outbound_discounted_price: () => LocalizedString
			}
			transactions: {
				/**
				 * Transactions
				 */
				title: () => LocalizedString
				/**
				 * Committed
				 */
				committed: () => LocalizedString
			}
		}
		isbn_tab: {
			titles: {
				/**
				 * Transactions
				 */
				transactions: () => LocalizedString
				/**
				 * History
				 */
				history: () => LocalizedString
			}
			isbn_id: {
				titles: {
					/**
					 * Stock
					 */
					stock: () => LocalizedString
				}
				placeholder_box: {
					/**
					 * No transactions found
					 */
					title: () => LocalizedString
					/**
					 * There seems to be no record of transactions for the given isbn volumes going in or out
					 */
					description: () => LocalizedString
				}
			}
			placeholder_box: {
				/**
				 * No book selected
				 */
				title: () => LocalizedString
				/**
				 * Use the search field to find the book you're looking for
				 */
				description: () => LocalizedString
			}
		}
		notes_tab: {
			date: {
				/**
				 * History
				 */
				history: () => LocalizedString
				/**
				 * Books
				 */
				books: () => LocalizedString
				/**
				 * Total cover price
				 */
				total_cover_price: () => LocalizedString
				/**
				 * Committed
				 */
				committed: () => LocalizedString
				/**
				 * Total discounted price
				 */
				total_discounted_price: () => LocalizedString
			}
			archive: {
				/**
				 * Committed At
				 */
				committed_at: () => LocalizedString
				/**
				 * Export CSV
				 */
				export_csv: () => LocalizedString
			}
		}
		warehouse_tab: {
			note_table: {
				filter_options: {
					/**
					 * All
					 */
					all: () => LocalizedString
					/**
					 * Inbound
					 */
					inbound: () => LocalizedString
					/**
					 * Outbound
					 */
					outbound: () => LocalizedString
				}
				column_headers: {
					/**
					 * quantity
					 */
					quantity: () => LocalizedString
					/**
					 * isbn
					 */
					isbn: () => LocalizedString
					/**
					 * title
					 */
					title: () => LocalizedString
					/**
					 * publisher
					 */
					publisher: () => LocalizedString
					/**
					 * authors
					 */
					authors: () => LocalizedString
					/**
					 * year
					 */
					year: () => LocalizedString
					/**
					 * price
					 */
					price: () => LocalizedString
					/**
					 * category
					 */
					category: () => LocalizedString
					/**
					 * edited_by
					 */
					edited_by: () => LocalizedString
					/**
					 * out_of_print
					 */
					out_of_print: () => LocalizedString
				}
				heading: {
					/**
					 * history
					 */
					history: () => LocalizedString
					/**
					 * Export CSV
					 */
					export_csv: () => LocalizedString
					/**
					 * From
					 */
					from: () => LocalizedString
					/**
					 * To
					 */
					to: () => LocalizedString
					/**
					 * Filter
					 */
					filter: () => LocalizedString
				}
				titles: {
					/**
					 * Transactions
					 */
					transactions: () => LocalizedString
				}
			}
			stats: {
				/**
				 * {no_of_books} book{{s}}
				 */
				books: (arg: { no_of_books: string | number | boolean }) => LocalizedString
				/**
				 * discount
				 */
				discount: () => LocalizedString
			}
		}
	}
	inventory_page: {
		inbound_tab: {
			placeholder_box: {
				/**
				 * No open notes
				 */
				title: () => LocalizedString
				/**
				 * Get started by adding a new note with the appropriate warehouse
				 */
				description: () => LocalizedString
			}
			stats: {
				/**
				 * Back to warehouses
				 */
				back_to_warehouses: () => LocalizedString
				/**
				 * {no_of_books} book{{s}}
				 */
				books: (arg: { no_of_books: string | number | boolean }) => LocalizedString
				/**
				 * Last Updated
				 */
				last_updated: () => LocalizedString
			}
			labels: {
				/**
				 * Edit
				 */
				button_edit: () => LocalizedString
			}
		}
	}
	orders_page: {
		/**
		 * Checkout
		 */
		checkout: () => LocalizedString
		/**
		 * Create a new Outbound Note
		 */
		create_outbound_note: () => LocalizedString
	}
	customer_orders_page: {
		/**
		 * Customer Orders
		 */
		title: () => LocalizedString
		/**
		 * New Order
		 */
		new_order: () => LocalizedString
		status_filters: {
			/**
			 * In Progress
			 */
			in_progress: () => LocalizedString
			/**
			 * Completed
			 */
			completed: () => LocalizedString
		}
		/**
		 * Customer
		 */
		customer: () => LocalizedString
		/**
		 * Order ID
		 */
		order_id: () => LocalizedString
		/**
		 * Update Order
		 */
		update_order: () => LocalizedString
		/**
		 * Customer Details
		 */
		customer_details: () => LocalizedString
		/**
		 * Update
		 */
		update: () => LocalizedString
	}
	suppliers_page: {
		/**
		 * New Supplier
		 */
		new_supplier: () => LocalizedString
		/**
		 * Suppliers
		 */
		suppliers: () => LocalizedString
		/**
		 * Delete
		 */
		'delete': () => LocalizedString
		/**
		 * Edit
		 */
		edit: () => LocalizedString
		supplierId: {
			new_order_page: {
				/**
				 * Total books
				 */
				total_books: () => LocalizedString
				/**
				 * Total value
				 */
				total_value: () => LocalizedString
				/**
				 * Books
				 */
				books: () => LocalizedString
				/**
				 * Select
				 */
				select: () => LocalizedString
				/**
				 * ISBN
				 */
				isbn: () => LocalizedString
				/**
				 * Title
				 */
				title: () => LocalizedString
				/**
				 * Authors
				 */
				authors: () => LocalizedString
				/**
				 * Ordered quantity
				 */
				ordered_quantity: () => LocalizedString
				/**
				 * Total
				 */
				total: () => LocalizedString
				/**
				 * Selected quantity
				 */
				selected_quantity: () => LocalizedString
				/**
				 * Selected books
				 */
				selected_books: () => LocalizedString
				/**
				 * Place Order
				 */
				place_order: () => LocalizedString
			}
			/**
			 * Supplier page
			 */
			supplier_page: () => LocalizedString
			/**
			 * Supplier name
			 */
			supplier_name: () => LocalizedString
			/**
			 * Supplier address
			 */
			supplier_address: () => LocalizedString
			/**
			 * Supplier email
			 */
			supplier_email: () => LocalizedString
			/**
			 * Create new order
			 */
			create_new_order: () => LocalizedString
			/**
			 * Assigned publishers
			 */
			assigned_publishers: () => LocalizedString
			/**
			 * Publisher name
			 */
			publisher_name: () => LocalizedString
			/**
			 * Remove publisher
			 */
			remove_publisher: () => LocalizedString
			/**
			 * Unassigned publishers
			 */
			unassigned_publishers: () => LocalizedString
			/**
			 * Add to supplier
			 */
			add_to_supplier: () => LocalizedString
		}
		orders_page: {
			/**
			 * Supplier Orders
			 */
			supplier_orders: () => LocalizedString
			/**
			 * Suppliers
			 */
			suppliers: () => LocalizedString
			/**
			 * Unordered
			 */
			unordered: () => LocalizedString
			/**
			 * Ordered
			 */
			ordered: () => LocalizedString
			/**
			 * Reconciling
			 */
			reconciling: () => LocalizedString
			/**
			 * Completed
			 */
			completed: () => LocalizedString
			no_unordered_books: {
				/**
				 * No unordered supplier orders available. Create a customer order first to generate supplier orders.
				 */
				description: () => LocalizedString
				/**
				 * New Customer Order
				 */
				button: () => LocalizedString
			}
			orderId: {
				reconciled_list: {
					/**
					 * View Reconciliation
					 */
					view_reconciliation: () => LocalizedString
					/**
					 * Reconcile
					 */
					reconcile: () => LocalizedString
					/**
					 * Total books
					 */
					total_books: () => LocalizedString
					/**
					 * Total value
					 */
					total_value: () => LocalizedString
					/**
					 * Ordered
					 */
					ordered: () => LocalizedString
					/**
					 * Print Order
					 */
					print_order: () => LocalizedString
					/**
					 * Books
					 */
					books: () => LocalizedString
					/**
					 * ISBN
					 */
					isbn: () => LocalizedString
					/**
					 * Title
					 */
					title: () => LocalizedString
					/**
					 * Authors
					 */
					authors: () => LocalizedString
					/**
					 * Quantity
					 */
					quantity: () => LocalizedString
					/**
					 * Total Price
					 */
					total_price: () => LocalizedString
				}
			}
		}
		reconcile_page: {
			/**
			 * Reconcile Deliveries
			 */
			reconcile_deliveries: () => LocalizedString
			/**
			 * Created
			 */
			created: () => LocalizedString
			/**
			 * Last Updated
			 */
			last_updated: () => LocalizedString
			/**
			 * Includes supplier orders
			 */
			includes_supplier_orders: () => LocalizedString
			/**
			 * Scan or enter the ISBNs of the delivered books to begin reconciliation.
			 */
			no_books: () => LocalizedString
			/**
			 * ISBN
			 */
			isbn: () => LocalizedString
			/**
			 * Title
			 */
			title: () => LocalizedString
			/**
			 * Authors
			 */
			authors: () => LocalizedString
			/**
			 * Quantity
			 */
			quantity: () => LocalizedString
			/**
			 * Price
			 */
			price: () => LocalizedString
			/**
			 * Total delivered
			 */
			total_delivered: () => LocalizedString
			delete_dialog: {
				/**
				 * Delete Reconciliation Order
				 */
				confirmDeleteDialogHeading: () => LocalizedString
				/**
				 * Are you sure you want to delete this reconciliation order? This action will delete all the scanned lines.
				 */
				confirmDeleteDialogDescription: () => LocalizedString
			}
		}
	}
	warehouse_list_page: {
		stats: {
			/**
			 * books
			 */
			books: () => LocalizedString
			/**
			 * discount
			 */
			discount: () => LocalizedString
		}
		labels: {
			/**
			 * New note
			 */
			new_note: () => LocalizedString
			/**
			 * View Stock
			 */
			view_stock: () => LocalizedString
		}
	}
	warehouse_page: {
		table: {
			/**
			 * Quantity
			 */
			quantity: () => LocalizedString
			/**
			 * ISBN
			 */
			isbn: () => LocalizedString
			/**
			 * Title
			 */
			title: () => LocalizedString
			/**
			 * Publisher
			 */
			publisher: () => LocalizedString
			/**
			 * Authors
			 */
			authors: () => LocalizedString
			/**
			 * Year
			 */
			year: () => LocalizedString
			/**
			 * Price
			 */
			price: () => LocalizedString
			/**
			 * Category
			 */
			category: () => LocalizedString
			/**
			 * Edited by
			 */
			edited_by: () => LocalizedString
			/**
			 * Out of print
			 */
			out_of_print: () => LocalizedString
		}
		labels: {
			/**
			 * Export to CSV
			 */
			export_to_csv: () => LocalizedString
			/**
			 * New note
			 */
			new_note: () => LocalizedString
			/**
			 * Edit row
			 */
			edit_row: () => LocalizedString
			/**
			 * Print book label
			 */
			print_book_label: () => LocalizedString
			/**
			 * Edit book details
			 */
			edit_book_details: () => LocalizedString
			/**
			 * Manually edit book details
			 */
			manually_edit_book_details: () => LocalizedString
		}
	}
	dialog_title: {
		/**
		 * Permenantly delete {entity}?
		 */
		'delete': (arg: { entity: unknown }) => LocalizedString
		/**
		 * Commit inbound {entity}?
		 */
		commit_inbound: (arg: { entity: unknown }) => LocalizedString
		/**
		 * Commit outbound {entity}?
		 */
		commit_outbound: (arg: { entity: unknown }) => LocalizedString
		/**
		 * No warehouse(s) selected
		 */
		no_warehouse_selected: () => LocalizedString
		/**
		 * Stock mismatch
		 */
		reconcile_outbound: () => LocalizedString
		/**
		 * Edit book details
		 */
		edit_book: () => LocalizedString
		/**
		 * Create custom item
		 */
		create_custom_item: () => LocalizedString
		/**
		 * Edit custom item
		 */
		edit_custom_item: () => LocalizedString
		/**
		 * Update book details
		 */
		edit_warehouse: () => LocalizedString
		/**
		 * Create new database
		 */
		create_database: () => LocalizedString
	}
	dialog_description: {
		/**
		 * Once you delete this note, you will not be able to access it again
		 */
		delete_note: () => LocalizedString
		/**
		 * Once you delete this warehouse {bookCount} book{{s}} will be removed from your stock
		 */
		delete_warehouse: (arg: { bookCount: string | number | boolean }) => LocalizedString
		/**
		 * Once you delete this database it can't be restored. In order to save the backup first, please use the export button.
		 */
		delete_database: () => LocalizedString
		/**
		 * {bookCount} book{{s}} will be added to {warehouseName}
		 */
		commit_inbound: (arg: { bookCount: string | number | boolean, warehouseName: unknown }) => LocalizedString
		/**
		 * {bookCount} book{{s}} will be removed from your stock
		 */
		commit_outbound: (arg: { bookCount: string | number | boolean }) => LocalizedString
		/**
		 * Can't commit the note as some transactions don't have any warehouse selected
		 */
		no_warehouse_selected: () => LocalizedString
		/**
		 * Some quantities requested are greater than available in stock and will need to be reconciled in order to proceed.
		 */
		reconcile_outbound: () => LocalizedString
		/**
		 * Update book details
		 */
		edit_book: () => LocalizedString
		/**
		 * Update warehouse details
		 */
		edit_warehouse: () => LocalizedString
		/**
		 * Please type in the name for the new database
		 */
		create_database: () => LocalizedString
	}
	outbound_note: {
		delete_dialog: {
			/**
			 * Please select a warehouse for each of the following transactions
			 */
			select_warehouse: () => LocalizedString
		}
		reconcile_dialog: {
			/**
			 * Please review the following transactions
			 */
			review_transaction: () => LocalizedString
			/**
			 * quantity for reconciliation
			 */
			quantity: () => LocalizedString
		}
		stats: {
			/**
			 * Last updated
			 */
			last_updated: () => LocalizedString
		}
		labels: {
			/**
			 * Delete
			 */
			'delete': () => LocalizedString
			/**
			 * Edit row
			 */
			edit_row: () => LocalizedString
			/**
			 * Print book label
			 */
			print_book_label: () => LocalizedString
			/**
			 * Delete row
			 */
			delete_row: () => LocalizedString
		}
	}
	outbound_page: {
		/**
		 * Outbound
		 */
		heading: () => LocalizedString
		stats: {
			/**
			 * Last updated
			 */
			last_updated: () => LocalizedString
			/**
			 * {bookCount} book{{s}}
			 */
			books: (arg: { bookCount: string | number | boolean }) => LocalizedString
		}
		labels: {
			/**
			 * New Note
			 */
			new_note: () => LocalizedString
			/**
			 * Edit
			 */
			edit: () => LocalizedString
			/**
			 * Print book label
			 */
			print_book_label: () => LocalizedString
			/**
			 * Delete row
			 */
			delete_row: () => LocalizedString
		}
	}
	inbound_note: {
		stats: {
			/**
			 * Last updated
			 */
			last_updated: () => LocalizedString
		}
		labels: {
			/**
			 * Commit
			 */
			commit: () => LocalizedString
			/**
			 * Print
			 */
			print: () => LocalizedString
			/**
			 * Auto print book labels
			 */
			auto_print_book_labels: () => LocalizedString
			/**
			 * Delete
			 */
			'delete': () => LocalizedString
			/**
			 * Edit row
			 */
			edit_row: () => LocalizedString
			/**
			 * Print book label
			 */
			print_book_label: () => LocalizedString
			/**
			 * Delete row
			 */
			delete_row: () => LocalizedString
		}
	}
	settings_page: {
		headings: {
			/**
			 * Settings
			 */
			settings: () => LocalizedString
			/**
			 * Device settings
			 */
			device_settings: () => LocalizedString
			/**
			 * Sync settings
			 */
			sync_settings: () => LocalizedString
			/**
			 * Database management
			 */
			db_management: () => LocalizedString
		}
		descriptions: {
			/**
			 * Manage DB name, sync URL and the connection. Note: This will be merged with DB selection in the future
			 */
			sync_settings: () => LocalizedString
			/**
			 * Use this section to create, select, import, export or delete a database
			 */
			db_management: () => LocalizedString
			/**
			 * Drag and drop your .sqlite3 file here to import
			 */
			'import': () => LocalizedString
			/**
			 * Manage connections to external devices
			 */
			device_settings: () => LocalizedString
		}
		stats: {
			/**
			 * Version
			 */
			version: () => LocalizedString
		}
		labels: {
			/**
			 * New
			 */
			'new': () => LocalizedString
		}
	}
	stock_page: {
		labels: {
			/**
			 * Edit book details
			 */
			edit_book_details: () => LocalizedString
			/**
			 * Manually edit book details
			 */
			manually_edit_book_details: () => LocalizedString
			/**
			 * Edit row
			 */
			edit_row: () => LocalizedString
			/**
			 * Print book label
			 */
			print_book_label: () => LocalizedString
		}
	}
}

export type Formatters = {}
