import { PUBLIC_DB_NAME, PUBLIC_COUCHDB_HOST, PUBLIC_COUCHDB_PORT, PUBLIC_COUCHDB_USER, PUBLIC_COUCHDB_PASSWORD } from "$env/static/public";

export const DB_NAME = PUBLIC_DB_NAME || "dev";

export const COUCHDB_PORT = PUBLIC_COUCHDB_PORT;
export const COUCHDB_HOST = PUBLIC_COUCHDB_HOST;
export const COUCHDB_USER = PUBLIC_COUCHDB_USER;
export const COUCHDB_PASSWORD = PUBLIC_COUCHDB_PASSWORD;
