// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from
'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
  | 'de'
  | 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
  nav: {
    /**
     * Search stock
     */
    search: string
    /**
     * Manage inventory
     */
    inventory: string
    /**
     * Outbound
     */
    outbound: string
    /**
     * Inbound
     */
    inbound: string
    /**
     * Settings
     */
    settings: string
    /**
     * History
     */
    history: string
    /**
     * Suppliers orders
     */
    supplier_orders: string
  }
  search: {
    /**
     * Search
     */
    title: string
    empty: {
      /**
       * Search for stock
       */
      title: string
      /**
       * Get started by searching by title, author, ISBN
       */
      description: string
    }
  },

}

export type TranslationFunctions = {
  nav: {
    /**
     * Search stock
     */
    search: () => LocalizedString
    /**
     * Manage inventory
     */
    inventory: () => LocalizedString
    /**
     * Outbound
     */
    outbound: () => LocalizedString
    /**
     * Inbound
     */
    inbound: () => LocalizedString
    /**
     * Settings
     */
    settings: () => LocalizedString
    /**
     * History
     */
    history: () => LocalizedString
    /**
     * Suppliers orders
     */
    supplier_orders: () => LocalizedString
  }
  search: {
    /**
     * Search
     */
    title: () => LocalizedString
    empty: {
      /**
       * Search for stock
       */
      title: () => LocalizedString
      /**
       * Get started by searching by title, author, ISBN
       */
      description: () => LocalizedString
    }
  },
  historyPage: {
    date: {
      stats: {
        title: () => LocalizedString,
        totalInboundBookCount: () => LocalizedString,
        totalInboundCoverPrice: () => LocalizedString,
        totalInboundDiscountedPrice: () => LocalizedString,
        totalOutboundBookCount: () => LocalizedString,
        totalOutboundCoverPrice: () => LocalizedString,
        totalOutboundDiscountedPrice: () => LocalizedString,
      },
      transactions: {
        title: () => LocalizedString,
        committed: () => LocalizedString,
      },
    },
    isbn: {
		transactions: () => LocalizedString,
		history: () => LocalizedString,
		isbnPage: {
			stock: () => LocalizedString,
			placeholderBox: {
				title: () => LocalizedString,
				description: () => LocalizedString
			}
		},
		placeholderBox: {
			title: () => LocalizedString,
			description:() => LocalizedString
		}
	},
	  notes: {
		  datePage: {
			  history: () => LocalizedString,
			  books: () => LocalizedString,
			  totalCoverPrice: () => LocalizedString,
			  committed: () => LocalizedString,
			  totalDiscountedPrice: () => LocalizedString

		  },
		  archivePage: {
			  exportCSV: () => LocalizedString,
			  committedAt: () => LocalizedString,

		  },

	  },
			warehouse: {
		  warehouseId: {
			  from: {
				  options: {
					  all: {
						  label: () => LocalizedString
					  },
					  inbound: {
						  label: () => LocalizedString
					  },
					  outbound: {
						  label: () => LocalizedString
					  }
				  },
						columnHeaders: {
							quantity:() => LocalizedString,
							isbn:() => LocalizedString,
							title:() => LocalizedString,
							publisher:() => LocalizedString,
							authors:() => LocalizedString,
							year:() => LocalizedString,
							price:() => LocalizedString,
							category:() => LocalizedString,
							editedBy:() => LocalizedString,
							outOfPrint:() => LocalizedString
						},
						heading: {
							history:() => LocalizedString,
							exportCSV:() => LocalizedString,
							from:() => LocalizedString,
							to:() => LocalizedString,
							filter:() => LocalizedString
						}
			  }
		  },
				books:()=>LocalizedString,
				discount: ()=>LocalizedString
	  }
  }
}

// export type historyPage = {
//   historyPage: {
//     date: {
//       stats: {
//         title: () => LocalizedString,
//         totalInboundBookCount: () => LocalizedString,
//         totalInboundCoverPrice: () => LocalizedString,
//         totalInboundDiscountedPrice: () => LocalizedString,
//         totalOutboundBookCount: () => LocalizedString,
//         totalOutboundCoverPrice: () => LocalizedString,
//         totalOutboundDiscountedPrice: () => LocalizedString,
//       },
//       transactions: {
//         title: () => LocalizedString,
//         committed: () => LocalizedString,
//       },
//     },
//     isbn: {
//       stock: () => LocalizedString
//     }
//   }
// }

export type Formatters = {}
