// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	nav: {
		/**
		 * S​e​a​r​c​h​ ​s​t​o​c​k
		 */
		search: string
		/**
		 * M​a​n​a​g​e​ ​i​n​v​e​n​t​o​r​y
		 */
		inventory: string
		/**
		 * O​u​t​b​o​u​n​d
		 */
		outbound: string
		/**
		 * I​n​b​o​u​n​d
		 */
		inbound: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
		/**
		 * H​i​s​t​o​r​y
		 */
		history: string
		/**
		 * S​u​p​p​l​i​e​r​s​ ​o​r​d​e​r​s
		 */
		supplier_orders: string
	}
	search: {
		/**
		 * S​e​a​r​c​h
		 */
		title: string
		empty: {
			/**
			 * S​e​a​r​c​h​ ​f​o​r​ ​s​t​o​c​k
			 */
			title: string
			/**
			 * G​e​t​ ​s​t​a​r​t​e​d​ ​b​y​ ​s​e​a​r​c​h​i​n​g​ ​b​y​ ​t​i​t​l​e​,​ ​a​u​t​h​o​r​,​ ​I​S​B​N
			 */
			description: string
		}
	}
	historyPage: {
		date: {
			stats: {
				/**
				 * S​t​a​t​s
				 */
				title: string
				/**
				 * I​n​b​o​u​n​d​ ​B​o​o​k​ ​C​o​u​n​t
				 */
				totalInboundBookCount: string
				/**
				 * I​n​b​o​u​n​d​ ​C​o​v​e​r​ ​P​r​i​c​e
				 */
				totalInboundCoverPrice: string
				/**
				 * I​n​b​o​u​n​d​ ​D​i​s​c​o​u​n​t​e​d​ ​P​r​i​c​e
				 */
				totalInboundDiscountedPrice: string
				/**
				 * O​u​t​b​o​u​n​d​ ​B​o​o​k​ ​C​o​u​n​t
				 */
				totalOutboundBookCount: string
				/**
				 * O​u​t​b​o​u​n​d​ ​C​o​v​e​r​ ​P​r​i​c​e
				 */
				totalOutboundCoverPrice: string
				/**
				 * O​u​t​b​o​u​n​d​ ​D​i​s​c​o​u​n​t​e​d​ ​P​r​i​c​e
				 */
				totalOutboundDiscountedPrice: string
			}
			transactions: {
				/**
				 * T​r​a​n​s​a​c​t​i​o​n​s
				 */
				title: string
				/**
				 * C​o​m​m​i​t​t​e​d
				 */
				committed: string
			}
		}
		isbn: {
			/**
			 * T​r​a​n​s​a​c​t​i​o​n​s
			 */
			transactions: string
			/**
			 * H​i​s​t​o​r​y
			 */
			history: string
			isbnId: {
				/**
				 * S​t​o​c​k
				 */
				stock: string
				placeholderBox: {
					/**
					 * N​o​ ​t​r​a​n​s​a​c​t​i​o​n​s​ ​f​o​u​n​d
					 */
					title: string
					/**
					 * T​h​e​r​e​ ​s​e​e​m​s​ ​t​o​ ​b​e​ ​n​o​ ​r​e​c​o​r​d​ ​o​f​ ​t​r​a​n​s​a​c​t​i​o​n​s​ ​f​o​r​ ​t​h​e​ ​g​i​v​e​n​ ​i​s​b​n​ ​v​o​l​u​m​e​s​ ​g​o​i​n​g​ ​i​n​ ​o​r​ ​o​u​t
					 */
					description: string
				}
			}
			placeholderBox: {
				/**
				 * N​o​ ​b​o​o​k​ ​s​e​l​e​c​t​e​d
				 */
				title: string
				/**
				 * U​s​e​ ​t​h​e​ ​s​e​a​r​c​h​ ​f​i​e​l​d​ ​t​o​ ​f​i​n​d​ ​t​h​e​ ​b​o​o​k​ ​y​o​u​'​r​e​ ​l​o​o​k​i​n​g​ ​f​o​r
				 */
				description: string
			}
		}
		notes: {
			datePage: {
				/**
				 * H​i​s​t​o​r​y
				 */
				history: string
				/**
				 * B​o​o​k​s
				 */
				books: string
				/**
				 * T​o​t​a​l​ ​c​o​v​e​r​ ​p​r​i​c​e
				 */
				totalCoverPrice: string
				/**
				 * C​o​m​m​i​t​t​e​d
				 */
				committed: string
				/**
				 * T​o​t​a​l​ ​d​i​s​c​o​u​n​t​e​d​ ​p​r​i​c​e
				 */
				totalDiscountedPrice: string
			}
			archivePage: {
				/**
				 * C​o​m​m​i​t​t​e​d​ ​A​t
				 */
				committedAt: string
				/**
				 * E​x​p​o​r​t​ ​C​S​V
				 */
				exportCSV: string
			}
		}
		warehouse: {
			warehouseId: {
				from: {
					options: {
						all: {
							/**
							 * A​l​l
							 */
							label: string
						}
						inbound: {
							/**
							 * I​n​b​o​u​n​d
							 */
							label: string
						}
						outbound: {
							/**
							 * O​u​t​b​o​u​n​d
							 */
							label: string
						}
					}
					columnHeaders: {
						/**
						 * q​u​a​n​t​i​t​y
						 */
						quantity: string
						/**
						 * i​s​b​n
						 */
						isbn: string
						/**
						 * t​i​t​l​e
						 */
						title: string
						/**
						 * p​u​b​l​i​s​h​e​r
						 */
						publisher: string
						/**
						 * a​u​t​h​o​r​s
						 */
						authors: string
						/**
						 * y​e​a​r
						 */
						year: string
						/**
						 * p​r​i​c​e
						 */
						price: string
						/**
						 * c​a​t​e​g​o​r​y
						 */
						category: string
						/**
						 * e​d​i​t​e​d​_​b​y
						 */
						editedBy: string
						/**
						 * o​u​t​_​o​f​_​p​r​i​n​t
						 */
						outOfPrint: string
					}
					heading: {
						/**
						 * h​i​s​t​o​r​y
						 */
						history: string
						/**
						 * E​x​p​o​r​t​ ​C​S​V
						 */
						exportCSV: string
						/**
						 * F​r​o​m
						 */
						from: string
						/**
						 * T​o
						 */
						to: string
						/**
						 * F​i​l​t​e​r
						 */
						filter: string
					}
					/**
					 * T​r​a​n​s​a​c​t​i​o​n​s
					 */
					transactions: string
				}
			}
			/**
			 * b​o​o​k​s
			 */
			books: string
			/**
			 * d​i​s​c​o​u​n​t
			 */
			discount: string
		}
	}
	inventoryPage: {
		inbound: {
			PlaceholderBox: {
				/**
				 * N​o​ ​o​p​e​n​ ​n​o​t​e​s
				 */
				title: string
				/**
				 * G​e​t​ ​s​t​a​r​t​e​d​ ​b​y​ ​a​d​d​i​n​g​ ​a​ ​n​e​w​ ​n​o​t​e​ ​w​i​t​h​ ​t​h​e​ ​a​p​p​r​o​p​r​i​a​t​e​ ​w​a​r​e​h​o​u​s​e
				 */
				description: string
			}
			/**
			 * B​a​c​k​ ​t​o​ ​w​a​r​e​h​o​u​s​e​s
			 */
			BackToWarehouses: string
			/**
			 * b​o​o​k​s
			 */
			books: string
			/**
			 * L​a​s​t​ ​U​p​d​a​t​e​d
			 */
			lastUpdated: string
			/**
			 * E​d​i​t
			 */
			edit: string
			inboundId: {
				/**
				 * L​a​s​t​ ​u​p​d​a​t​e​d
				 */
				lastUpdated: string
				/**
				 * C​o​m​m​i​t
				 */
				commit: string
				/**
				 * P​r​i​n​t
				 */
				print: string
				/**
				 * A​u​t​o​ ​p​r​i​n​t​ ​b​o​o​k​ ​l​a​b​e​l​s
				 */
				autoPrintBookLabels: string
				/**
				 * D​e​l​e​t​e
				 */
				'delete': string
				/**
				 * E​d​i​t​ ​r​o​w
				 */
				editRow: string
				/**
				 * P​r​i​n​t​ ​b​o​o​k​ ​l​a​b​e​l
				 */
				printBookLabel: string
				/**
				 * D​e​l​e​t​e​ ​r​o​w
				 */
				deleteRow: string
			}
		}
		outbound: {
			PlaceholderBox: {
			}
		}
	}
}

export type TranslationFunctions = {
	nav: {
		/**
		 * Search stock
		 */
		search: () => LocalizedString
		/**
		 * Manage inventory
		 */
		inventory: () => LocalizedString
		/**
		 * Outbound
		 */
		outbound: () => LocalizedString
		/**
		 * Inbound
		 */
		inbound: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * History
		 */
		history: () => LocalizedString
		/**
		 * Suppliers orders
		 */
		supplier_orders: () => LocalizedString
	}
	search: {
		/**
		 * Search
		 */
		title: () => LocalizedString
		empty: {
			/**
			 * Search for stock
			 */
			title: () => LocalizedString
			/**
			 * Get started by searching by title, author, ISBN
			 */
			description: () => LocalizedString
		}
	}
	historyPage: {
		date: {
			stats: {
				/**
				 * Stats
				 */
				title: () => LocalizedString
				/**
				 * Inbound Book Count
				 */
				totalInboundBookCount: () => LocalizedString
				/**
				 * Inbound Cover Price
				 */
				totalInboundCoverPrice: () => LocalizedString
				/**
				 * Inbound Discounted Price
				 */
				totalInboundDiscountedPrice: () => LocalizedString
				/**
				 * Outbound Book Count
				 */
				totalOutboundBookCount: () => LocalizedString
				/**
				 * Outbound Cover Price
				 */
				totalOutboundCoverPrice: () => LocalizedString
				/**
				 * Outbound Discounted Price
				 */
				totalOutboundDiscountedPrice: () => LocalizedString
			}
			transactions: {
				/**
				 * Transactions
				 */
				title: () => LocalizedString
				/**
				 * Committed
				 */
				committed: () => LocalizedString
			}
		}
		isbn: {
			/**
			 * Transactions
			 */
			transactions: () => LocalizedString
			/**
			 * History
			 */
			history: () => LocalizedString
			isbnId: {
				/**
				 * Stock
				 */
				stock: () => LocalizedString
				placeholderBox: {
					/**
					 * No transactions found
					 */
					title: () => LocalizedString
					/**
					 * There seems to be no record of transactions for the given isbn volumes going in or out
					 */
					description: () => LocalizedString
				}
			}
			placeholderBox: {
				/**
				 * No book selected
				 */
				title: () => LocalizedString
				/**
				 * Use the search field to find the book you're looking for
				 */
				description: () => LocalizedString
			}
		}
		notes: {
			datePage: {
				/**
				 * History
				 */
				history: () => LocalizedString
				/**
				 * Books
				 */
				books: () => LocalizedString
				/**
				 * Total cover price
				 */
				totalCoverPrice: () => LocalizedString
				/**
				 * Committed
				 */
				committed: () => LocalizedString
				/**
				 * Total discounted price
				 */
				totalDiscountedPrice: () => LocalizedString
			}
			archivePage: {
				/**
				 * Committed At
				 */
				committedAt: () => LocalizedString
				/**
				 * Export CSV
				 */
				exportCSV: () => LocalizedString
			}
		}
		warehouse: {
			warehouseId: {
				from: {
					options: {
						all: {
							/**
							 * All
							 */
							label: () => LocalizedString
						}
						inbound: {
							/**
							 * Inbound
							 */
							label: () => LocalizedString
						}
						outbound: {
							/**
							 * Outbound
							 */
							label: () => LocalizedString
						}
					}
					columnHeaders: {
						/**
						 * quantity
						 */
						quantity: () => LocalizedString
						/**
						 * isbn
						 */
						isbn: () => LocalizedString
						/**
						 * title
						 */
						title: () => LocalizedString
						/**
						 * publisher
						 */
						publisher: () => LocalizedString
						/**
						 * authors
						 */
						authors: () => LocalizedString
						/**
						 * year
						 */
						year: () => LocalizedString
						/**
						 * price
						 */
						price: () => LocalizedString
						/**
						 * category
						 */
						category: () => LocalizedString
						/**
						 * edited_by
						 */
						editedBy: () => LocalizedString
						/**
						 * out_of_print
						 */
						outOfPrint: () => LocalizedString
					}
					heading: {
						/**
						 * history
						 */
						history: () => LocalizedString
						/**
						 * Export CSV
						 */
						exportCSV: () => LocalizedString
						/**
						 * From
						 */
						from: () => LocalizedString
						/**
						 * To
						 */
						to: () => LocalizedString
						/**
						 * Filter
						 */
						filter: () => LocalizedString
					}
					/**
					 * Transactions
					 */
					transactions: () => LocalizedString
				}
			}
			/**
			 * books
			 */
			books: () => LocalizedString
			/**
			 * discount
			 */
			discount: () => LocalizedString
		}
	}
	inventoryPage: {
		inbound: {
			PlaceholderBox: {
				/**
				 * No open notes
				 */
				title: () => LocalizedString
				/**
				 * Get started by adding a new note with the appropriate warehouse
				 */
				description: () => LocalizedString
			}
			/**
			 * Back to warehouses
			 */
			BackToWarehouses: () => LocalizedString
			/**
			 * books
			 */
			books: () => LocalizedString
			/**
			 * Last Updated
			 */
			lastUpdated: () => LocalizedString
			/**
			 * Edit
			 */
			edit: () => LocalizedString
			inboundId: {
				/**
				 * Last updated
				 */
				lastUpdated: () => LocalizedString
				/**
				 * Commit
				 */
				commit: () => LocalizedString
				/**
				 * Print
				 */
				print: () => LocalizedString
				/**
				 * Auto print book labels
				 */
				autoPrintBookLabels: () => LocalizedString
				/**
				 * Delete
				 */
				'delete': () => LocalizedString
				/**
				 * Edit row
				 */
				editRow: () => LocalizedString
				/**
				 * Print book label
				 */
				printBookLabel: () => LocalizedString
				/**
				 * Delete row
				 */
				deleteRow: () => LocalizedString
			}
		}
		outbound: {
			PlaceholderBox: {
			}
		}
	}
}

export type Formatters = {}
