#@ def cache_node():
name: Cache node modules
uses: actions/cache@v3
with:
    path: |
        ~/.rush
        ~/.pnpm-store
        common/temp
        **/node_modules
    key: ${{ runner.os }}-modules-node18-v2-${{ hashFiles('**/pnpm-lock.yaml') }}
#@ end
