#@ def cache_node():
name: Cache node modules
uses: actions/cache@v4
with:
  path: |
    ~/.rush
    ~/.pnpm-store
    common/temp
    ./common/temp/node_modules/
  key: ${{ runner.os }}-modules-node16-v3-${{ hashFiles('**/pnpm-lock.yaml') }}
#@ end
