#@ def checkout(deep=None):
name: Checkout repository and submodules
uses: actions/checkout@v4
with:
  submodules: "recursive"
  lfs: false
  #@ if deep!=None:
  fetch-depth: 0  #! Enables full clone, with all history
  #@ end
#@ end
