#@ def checkout(fetch_depth=None):
name: Checkout repository
uses: actions/checkout@v3
#@ if fetch_depth != None:
with:
  fetch-depth: #@ fetch_depth
#@ end
#@ end

#@ def cache_node():
name: Cache node modules
uses: actions/cache@v3
with:
  path: |
    ~/.rush
    ~/.pnpm-store
    common/temp
    **/node_modules
  key: ${{ runner.os }}-modules-node16-v1-${{ hashFiles('**/pnpm-lock.yaml') }}
#@ end

#@ def save_current_sha():
name: Determine current git SHA and set it for subsequent steps
run: echo CURRENT_SHA=$(git rev-parse --short HEAD) >> $GITHUB_ENV
#@ end
