#@ load("cache.lib.yml", "cache_node")

name: Lint and typecheck the packages

"on":
  - push

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - #@ cache_node()
      - name: Add local rush scripts to PATH
        run: echo "${PWD}"/common/scripts >> $GITHUB_PATH
      - name: Install and build packages
        run: rush update && rush build
      - name: Lint all the packages
        run: rush lint:strict
      - name: Typecheck all the packages
        #! Run typecheck even if linting fails
        if: success() || failure()
        run: rush typecheck
