#@ load("cache.lib.yml", "cache_node")
#@ load("rush.lib.yml", "rush_add_path")
#@ load("rush.lib.yml", "rush_install")
#@ load("rush.lib.yml", "rush_build")

name: Cheks

"on":
  - push

jobs:
  js-search-test:
    name: JS-Search tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      -  #@ cache_node()
      -  #@ rush_add_path()
      -  #@ rush_install()
      - name: Run tests
        run: cd pkg/js-search/ && rushx test:ci
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JS-Search Tests
          path: pkg/js-search/junit.xml
          reporter: jest-junit
      - name: Build js-search
        run: cd pkg/js-search/ && rushx build
  lint-and-typecheck:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      -  #@ cache_node()
      -  #@ rush_add_path()
      -  #@ rush_install()
      -  #@ rush_build()
      - name: Lint all the packages
        run: rush lint:strict
      - name: Typecheck all the packages
        #! Run typecheck even if linting fails
        if: success() || failure()
        run: rush typecheck
