#@ load("cache.lib.yml", "cache_node")
#@ load("rush.lib.yml", "rush_add_path")
#@ load("rush.lib.yml", "rush_install")
#@ load("rush.lib.yml", "rush_build")

name: PlaywrightMatrix

"on":
  push:
    branches:
      - "playwright-matrix/**"
  schedule:
    - cron: "30 5 * * 1,3"

jobs:
  e2e-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dummy1: [1, 2, 3, 4, 5, 6]
        dummy2: [1, 2, 3, 4, 5, 6]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      -  #@ cache_node()
      -  #@ rush_add_path()
      -  #@ rush_install()
      -  #@ rush_build()
      - name: Build the app
        run: cd apps/web-client && rushx build:prod
      - name: Run Playwright tests
        run: cd apps/e2e && rushx test:ci
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-test-results
          path: apps/e2e/test-results
          retention-days: 30
