#@ load("github.lib.yml", "checkout")
#@ load("github.lib.yml", "load_artefacts")
#@ load("cache.lib.yml", "cache_node")
#@ load("cache.lib.yml", "load_cached_artefacts")
#@ load("rush.lib.yml", "rush_add_path")
#@ load("rush.lib.yml", "rush_install")
#@ load("rush.lib.yml", "rush_build")
#@ load("build-crsqlite.lib.yml", "build_crsqlite")

name: PlaywrightMatrix

"on":
  push:
    branches:
      - "playwright-matrix/**"

  schedule:
    - cron: "30 5 * * 1,3"

jobs:
  build-cr-sqlite: #@ build_crsqlite()

  e2e-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: build-cr-sqlite
    strategy:
      fail-fast: false
      matrix:
        dummy1: [1, 2, 3, 4, 5, 6]
        dummy2: [1, 2, 3, 4, 5, 6]
    steps:
      -  #@ checkout()
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      -  #@ load_artefacts()
      -  #@ load_cached_artefacts()
      -  #@ cache_node()
      -  #@ rush_add_path()
      -  #@ rush_install()
      -  #@ rush_build()
      - name: Build the app
        run: cd apps/web-client && rushx build:e2e
      - name: Download playwright browsers
        run: cd apps/e2e && npx playwright install
      - name: Run Playwright tests
        run: cd apps/e2e && rushx test:ci
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-results-${{ matrix.dummy1 }}-${{ matrix.dummy2 }}
          path: apps/e2e/test-results
          retention-days: 30
