#@ load("github.lib.yml", "checkout")
#@ load("cache.lib.yml", "cache_node")
#@ load("rush.lib.yml", "rush_add_path")
#@ load("rush.lib.yml", "rush_install")
#@ load("rush.lib.yml", "rush_build")

name: PyInstaller Build

"on":
  push:
    paths:
      - "python-apps/**"
      - "apps/web-client/**"
      - ".github/workflows/pyinstaller-build.yml"
  workflow_dispatch:

jobs:
  #! Check if we should build (main branch OR [build-pyinstaller] in commit message)
  check-trigger:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.check.outputs.should_build }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Check trigger conditions
        id: check
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "should_build=true" >> "$GITHUB_OUTPUT"
            echo "Building because pushed to main branch"
            exit 0
          fi

          if git log -1 --pretty=%B | grep -q '\[build-pyinstaller\]'; then
            echo "should_build=true" >> "$GITHUB_OUTPUT"
            echo "Building because commit message contains [build-pyinstaller]"
            exit 0
          fi

          echo "should_build=false" >> "$GITHUB_OUTPUT"
          echo "Skipping build - not on main and no [build-pyinstaller] tag"

  build-executable:
    needs: check-trigger
    if: needs.check-trigger.outputs.should_build == 'true'
    name: Build ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          #! Linux builds
          - os: linux
            arch: x64
            runner: ubuntu-latest
            artifact_name: librocco-launcher-linux-x64
          #! NOTE: Linux ARM64 - GitHub doesn't provide native ARM64 runners yet
          #! We could use QEMU or cross-compilation, but skipping for now
          #! - os: linux
          #!   arch: arm64
          #!   runner: ubuntu-latest
          #!   artifact_name: librocco-launcher-linux-arm64

          #! macOS builds
          - os: macos
            arch: x64
            runner: macos-13  #! Intel runner
            artifact_name: librocco-launcher-macos-x64
          - os: macos
            arch: arm64
            runner: macos-14  #! Apple Silicon runner
            artifact_name: librocco-launcher-macos-arm64

          #! Windows builds
          - os: windows
            arch: x64
            runner: windows-latest
            artifact_name: librocco-launcher-windows-x64
          #! NOTE: Windows ARM64 - GitHub doesn't provide ARM64 runners yet
          #! - os: windows
          #!   arch: arm64
          #!   runner: windows-latest
          #!   artifact_name: librocco-launcher-windows-arm64

    steps:
      -  #@ checkout()

      #! Node.js setup for web-client build
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      #! Python setup
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      #! Install uv
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      #! Cache node modules
      -  #@ cache_node()

      #! Install Rush globally
      - name: Install Rush
        run: npm install -g @microsoft/rush

      #! Add Rush scripts to PATH
      -  #@ rush_add_path()

      #! Build web client
      -  #@ rush_install()
      -  #@ rush_build()

      - name: Build web-client for root path
        run: cd apps/web-client && rushx build:prod-rootdir
        shell: bash

      #! Build executable
      - name: Build PyInstaller executable
        run: |
          cd python-apps/launcher
          uv run scripts/build_executable.py
        shell: bash

      #! Upload artifacts
      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            python-apps/launcher/dist/librocco-launcher*
          retention-days: 90
          if-no-files-found: error

      #! Quick smoke test - just verify the executable exists and can show help
      - name: Smoke test (Unix)
        if: runner.os != 'Windows'
        run: |
          cd python-apps/launcher/dist
          chmod +x librocco-launcher
          timeout 5 ./librocco-launcher --help || true
        shell: bash

      - name: Smoke test (Windows)
        if: runner.os == 'Windows'
        run: |
          cd python-apps/launcher/dist
          if (Test-Path librocco-launcher.exe) {
            Write-Host "Executable built successfully"
          } else {
            Write-Error "Executable not found!"
            exit 1
          }
        shell: pwsh
