#@ def rush_add_path():
name: Add local rush scripts to PATH
run: echo "${PWD}"/common/scripts >> $GITHUB_PATH
#@ end
---
#@ def rush_install():
name: Install packages
run: rush install
#@ end
---
#@ def rush_build():
name: Build packages
run: |
  set +e
  rush build
  exit_code=$?
  if [ $exit_code -eq 0 ] || [ $exit_code -eq 1 ]; then
    echo "Build completed (exit code: $exit_code)"
    exit 0
  else
    echo "Build failed with exit code: $exit_code"
    exit $exit_code
  fi
#@ end

