#@ load("github.lib.yml", "checkout")
#@ load("github.lib.yml", "pull_artefacts")
#@ load("cache.lib.yml", "cache_node")
#@ load("cache.lib.yml", "load_cached_artefacts")
#@ load("rush.lib.yml", "rush_add_path")
#@ load("rush.lib.yml", "rush_install")
#@ load("r2.lib.yml", "install_and_configure_rclone")
#@ load("r2.lib.yml", "upload_to_r2")

name: Site CI

"on":
  push:
    branches-ignore:
      - "ci-debug/*"
      - "wip/**"
    paths:
      - "apps/site/**"
      - ".github/workflow.templates/site-ci.yml"

jobs:
  deploy-preview-site:
    name: Deploy preview site to R2
    runs-on: ubuntu-latest
    steps:
      -  #@ checkout()
      -  #@ pull_artefacts()
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Compute desired compiled artifact version
        run: ./scripts/compute_artefacts_version.sh
      -  #@ load_cached_artefacts()
      -  #@ cache_node()
      -  #@ rush_add_path()
      -  #@ rush_install()
      - name: Build site using prefix ${{ github.head_ref || github.ref_name }}
        run: cd apps/site && rushx build
        env:
          BASE_PATH: /${{ github.head_ref || github.ref_name }}/site
      -  #@ install_and_configure_rclone()
      -  #@ upload_to_r2("apps/site/dist/", "${{ github.head_ref || github.ref_name }}/site/")
      - name: Output link to deployed site
        run: echo You can view the site on https://test.libroc.co/${{ github.head_ref || github.ref_name }}/site/index.html | tee -a $GITHUB_STEP_SUMMARY
