#@ load("github.lib.yml", "checkout")
#@ load("github.lib.yml", "load_artefacts")
#@ load("cache.lib.yml", "load_cached_artefacts")
#@ load("cache.lib.yml", "cache_node")
#@ load("rush.lib.yml", "rush_add_path")
#@ load("rush.lib.yml", "rush_install")
#@ load("rush.lib.yml", "rush_build")

#@ def test_script(workdir):
#@  return "cd "+workdir+" && rushx test:ci"
#@ end

#@ def test_job(name, workdir, reporter=None):
name: #@ name
runs-on: ubuntu-latest
timeout-minutes: 10
needs: build-cr-sqlite
permissions:
  id-token: write
  contents: read
  checks: write
steps:
  -  #@ checkout()
  - uses: actions/setup-node@v4
    with:
      node-version: "20"
  - name: Compute desired compiled artifact version
    run: ./scripts/compute_artefacts_version.sh #! This will inform the cache to load the correct artefacts
  -  #@ load_artefacts()
  -  #@ load_cached_artefacts()
  -  #@ cache_node()
  -  #@ rush_add_path()
  -  #@ rush_install()
  -  #@ rush_build()
  - name: Run tests
    run: #@ test_script(workdir)
  #@ if reporter!=None:
  - name: Test Report
    uses: dorny/test-reporter@v1
    if: success() || failure()
    with:
      name: #@ name
      path: #@ workdir+"/junit.xml"
      reporter: #@ reporter
  #@ end
#@ end
