#@ load("github.lib.yml", "checkout", "cache_node")
#@ load("rush.lib.yml", "rush_add_path", "rush_install", "rush_build")
#@ load("ncftp.lib.yml", "install_ncftp", "ncftp_bunny_copy")

#@ def deploy():
name: Deploy web-client app to bunny cdn
runs-on: ubuntu-latest
steps:
  - uses: actions/setup-node@v3
    with:
        node-version: "16"
  -  #@ checkout()
  -  #@ cache_node()
  -  #@ rush_add_path()
  -  #@ rush_install()
  -  #@ rush_build()
  - name: Build web-client app using prefix ${{ github.head_ref || github.ref_name }}
    run: cd apps/web-client && rushx build:prod
    env:
      NODE_ENV: deployment
      BASE_PATH: ${{ github.head_ref || github.ref_name }}
  -  #@ install_ncftp()
  -  #@ ncftp_bunny_copy(name="built app", src="apps/web-client/build/*", dst="${{ github.head_ref || github.ref_name }}")
  - name: Purge bunny cache
    run: 'curl --request POST --url https://api.bunny.net/pullzone/1306302/purgeCache --header "content-type: application/json" --header "AccessKey: $BUNNY_API_KEY"'
    env:
      BUNNY_API_KEY: ${{ secrets.BUNNY_API_KEY }}
  - name: Output link to deployed app
    run: echo You can view the app on https://test.libroc.co/${{ github.head_ref || github.ref_name }}/index.html | tee -a $GITHUB_STEP_SUMMARY
#@ end
