#@ def build_windows_crsqlite():
#! TEMPORARY WORKAROUND for Windows cr-sqlite builds
#! This job builds crsqlite.dll on Windows because the upstream Makefile
#! doesn't properly handle MSVC's .lib extension (expects Unix .a files).
#! When upstream fixes Windows support, this entire job can be removed.
#! See: https://github.com/vlcn-io/cr-sqlite/issues (Windows MSVC support)

runs-on: windows-latest
outputs:
  artifact_name: ${{ steps.output.outputs.artifact_name }}
steps:
  #! Don't checkout main repo - we need to clone cr-sqlite instead
  #! - uses: actions/checkout@v4

  #! Install Rust for Windows MSVC target
  - name: Install Rust Toolchain
    uses: actions-rs/toolchain@v1
    with:
      toolchain: nightly-2023-10-05
      target: x86_64-pc-windows-msvc
      override: true

  #! Configure git to use HTTPS instead of SSH for submodules
  - name: Configure git for HTTPS
    shell: bash
    run: |
      git config --global url."https://github.com/".insteadOf "git@github.com:"

  #! Clone the cr-sqlite repository at the version we need (0.16.3)
  - name: Clone cr-sqlite repository
    shell: pwsh
    run: |
      git clone --recurse-submodules --depth 1 --branch v0.16.3 https://github.com/vlcn-io/cr-sqlite.git cr-sqlite-build

      if ($LASTEXITCODE -ne 0) {
        Write-Error "Git clone failed"
        exit 1
      }

      Set-Location cr-sqlite-build
      git log -1 --oneline
      Get-ChildItem

  #! Try building with make loadable
  - name: Build crsqlite.dll with make
    shell: bash
    working-directory: cr-sqlite-build/core
    run: |
      # Try using make (might work with Git Bash on Windows)
      make loadable || {
        echo "Make failed, will try manual build next"
        exit 1
      }

      ls -la dist/

  #! Upload the built DLL as an artifact
  - name: Upload Windows crsqlite.dll
    uses: actions/upload-artifact@v4
    with:
      name: crsqlite-windows-dll
      path: cr-sqlite-build/core/dist/crsqlite.dll
      retention-days: 90
      if-no-files-found: error

  #! Set output for downstream jobs
  - name: Set output
    id: output
    shell: bash
    run: echo "artifact_name=crsqlite-windows-dll" >> "$GITHUB_OUTPUT"

#@ end
