name: JS-Search tests

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.rush
            ~/.pnpm-store
            common/temp
            **/node_modules
          key: ${{ runner.os }}-modules-node16-v1-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install packages
        run: node common/scripts/install-run-rush.js update
      - name: Run tests
        run: cd pkg/js-search/ && ./node_modules/.bin/jest
